name = "SmoothedDifferentiation"
uuid = "1059cf8c-97d7-4ea5-b71f-68a0f14697c4"
authors = ["Anonymous"]
version = "0.1.3-DEV"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
XAIBase = "9b48221d-a747-4c1b-9860-46a1d8ba24a7"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[weakdeps]
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"

[extensions]
SmoothedDifferentiationMetalheadExt = "Metalhead"

[compat]
ChainRulesCore = "1"
Distributions = "0.25"
Flux = "0.14, 0.15, 0.16"
Metalhead = "0.9.5"
NNlib = "0.9"
ProgressMeter = "1"
Random = "1"
Reexport = "1"
Statistics = "1"
XAIBase = "4"
Zygote = "0.6"
julia = "1.10"
